#!/bin/bash

# Todo (in priority order): 
#   - create restore option
#   - create a rollback option
#   - combined option parsing (i.e., -iv is equivalent to -i -v)
#   - create and install manpage
#   - implement delete option

BASEDIR=$(dirname $0)

. $BASEDIR/trashman/common.sh

main() {
    initialize
    parseOpts $@

    case $ACTION in
        "EMPTY")
            . $BASEDIR/trashman/trash.sh
            empty
            exit
            ;;
        "HELP")
            usage
            exit
            ;;
        "HISTORY")
            . $BASEDIR/trashman/history.sh
            listHistory
            exit
            ;;
        "RESTORE")
            . $BASEDIR/trashman/restore.sh
            restore
            ;;
        "ROLLBACK")
            ;;
        "TRASH")
            . $BASEDIR/trashman/trash.sh
            trash
            exit
            ;;
        "VERSION")
            echo "trashman $VERSION"
            exit
            ;;
    esac
}

main $@
